version: '3.8'

services:
  backend:
    build:
      context: ./backend-services
    container_name: backend-services
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-ui
    ports:
      - "5173:5173"
